# Generated by Django 5.2.8 on 2025-11-14 14:12

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NavigationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('url', models.CharField(blank=True, max_length=200)),
                ('is_dropdown', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Descriptive name for this content section', max_length=100)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Description of this content section')),
                ('layout', models.CharField(choices=[('hero', 'Hero'), ('grid-3', '3-Col Cards'), ('stats', 'Stats Grid'), ('list', 'Bullet List')], default='grid-3', help_text='Layout template used to display this section', max_length=20)),
                ('rows', models.PositiveIntegerField(default=1)),
                ('columns', models.PositiveIntegerField(default=3)),
                ('card_gap', models.CharField(default='1.5rem', max_length=20)),
                ('vertical_alignment', models.CharField(choices=[('start', 'Top'), ('center', 'Center'), ('end', 'Bottom')], default='start', max_length=20)),
                ('horizontal_alignment', models.CharField(choices=[('start', 'Left'), ('center', 'Center'), ('end', 'Right')], default='center', max_length=20)),
                ('section_bg_color', models.CharField(default='#ffffff', max_length=7)),
                ('section_text_color', models.CharField(default='#000000', max_length=7)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Ethiotech Leader', max_length=100)),
                ('logo_text', models.CharField(blank=True, help_text='e.g., [Logo] or leave blank', max_length=50)),
                ('logo', models.ImageField(blank=True, help_text='Upload your logo image', null=True, upload_to='logos/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='favicon/')),
            ],
            options={
                'verbose_name': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='DropdownItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dropdown_items', to='core.navigationitem')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CardBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Card title displayed prominently', max_length=200)),
                ('text', django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Rich text content for the card')),
                ('icon', models.CharField(help_text='Lucide icon name (e.g. rocket-launch)', max_length=60)),
                ('icon_size', models.PositiveIntegerField(default=32, help_text='Icon size in pixels')),
                ('icon_color', models.CharField(default='#3b82f6', help_text='Icon color in HEX format', max_length=7)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cards/')),
                ('image_alt', models.CharField(blank=True, max_length=200)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('video_thumbnail', models.ImageField(blank=True, null=True, upload_to='video_thumbnails/')),
                ('video_url', models.URLField(blank=True)),
                ('button_label', models.CharField(blank=True, max_length=100)),
                ('button_url', models.URLField(blank=True)),
                ('button_color', models.CharField(default='#3b82f6', max_length=7)),
                ('button_text_color', models.CharField(default='#ffffff', max_length=7)),
                ('button_target', models.CharField(blank=True, choices=[('_self', 'Same Tab'), ('_blank', 'New Tab')], default='_self', max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_block', to='core.section')),
            ],
            options={
                'verbose_name': 'Card Block',
                'verbose_name_plural': 'Card Blocks',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='section',
            name='site_settings',
            field=models.ForeignKey(help_text='Site settings this section belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='core.sitesettings'),
        ),
    ]
