# Generated by Django 5.2.8 on 2025-11-14 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='site_settings',
        ),
        migrations.AddField(
            model_name='navigationitem',
            name='button_color',
            field=models.CharField(default='#3b82f6', max_length=7),
        ),
        migrations.AddField(
            model_name='navigationitem',
            name='button_label',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='navigationitem',
            name='button_target',
            field=models.CharField(blank=True, choices=[('_self', 'Same Tab'), ('_blank', 'New Tab')], default='_self', max_length=10),
        ),
        migrations.AddField(
            model_name='navigationitem',
            name='button_text_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
        migrations.AddField(
            model_name='navigationitem',
            name='button_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='navigationitem',
            name='is_button',
            field=models.BooleanField(default=False),
        ),
    ]
