# Generated by Django 5.2.8 on 2025-11-14 14:31

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_section_site_settings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardblock',
            name='button_color',
            field=colorfield.fields.ColorField(default='#3b82f6', help_text='Button color in HEX format', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='cardblock',
            name='button_text_color',
            field=colorfield.fields.ColorField(default='#ffffff', help_text='Button text color in HEX format', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='cardblock',
            name='icon_color',
            field=colorfield.fields.ColorField(default='#3b82f6', help_text='Icon color in HEX format', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='navigationitem',
            name='button_color',
            field=colorfield.fields.ColorField(default='#3b82f6', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='navigationitem',
            name='button_text_color',
            field=colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='section',
            name='section_bg_color',
            field=colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='section',
            name='section_text_color',
            field=colorfield.fields.ColorField(default='#000000', image_field=None, max_length=25, samples=None),
        ),
    ]
