# Generated by Django 5.2.8 on 2025-11-14 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_cardblock_button_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
