# Generated by Django 5.2.8 on 2025-11-14 15:37

import colorfield.fields
import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sitesettings_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Main heading. Plain text (no rich text editor).', max_length=200)),
                ('subtitle_description', django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Supporting text. Rich text editor enabled.')),
                ('cta_text', models.CharField(blank=True, help_text='Call-to-Action button text', max_length=100)),
                ('cta_link', models.URLField(blank=True, help_text='Call-to-Action button URL')),
                ('cta_bg_color', colorfield.fields.ColorField(default='#3b82f6', help_text='Button background color', image_field=None, max_length=25, samples=None)),
                ('layout_type', models.CharField(choices=[('text-left-image-right', 'Text Left / Image Right'), ('text-right-image-left', 'Text Right / Image Left'), ('text-center-image-background', 'Text Center / Image Background'), ('text-center-no-image', 'Text Center / No Image')], default='text-center-image-background', help_text='Descriptive layout type', max_length=50)),
                ('rotating_text_settimeout', models.PositiveIntegerField(default=3000, help_text='Delay (ms) for text rotation')),
                ('image_settimeout', models.PositiveIntegerField(default=5000, help_text='Delay (ms) for background image rotation')),
                ('bg_color', colorfield.fields.ColorField(default='#ffffff', help_text='Background color for the Hero section', image_field=None, max_length=25, samples=None)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Hero Section',
                'verbose_name_plural': 'Hero Sections',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HeroBackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Image file for the background slider', upload_to='hero_backgrounds/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Used for sorting the slide rotation')),
                ('hero', models.ForeignKey(help_text='Parent Hero section', on_delete=django.db.models.deletion.CASCADE, related_name='background_images', to='core.hero')),
            ],
            options={
                'verbose_name': 'Hero Background Image',
                'verbose_name_plural': 'Hero Background Images',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='RotatingTextItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='The individual text string to be rotated', max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('hero', models.ForeignKey(help_text='Parent Hero section', on_delete=django.db.models.deletion.CASCADE, related_name='rotating_texts', to='core.hero')),
            ],
            options={
                'verbose_name': 'Rotating Text Item',
                'verbose_name_plural': 'Rotating Text Items',
                'ordering': ['order'],
            },
        ),
    ]
