# Generated by Django 5.2.8 on 2025-11-14 16:14

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_hero_herobackgroundimage_rotatingtextitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardblock',
            name='card_bg_color',
            field=colorfield.fields.ColorField(default='#ffffff', help_text='Card background color', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='cardblock',
            name='card_text_color',
            field=colorfield.fields.ColorField(default='#000000', help_text='Card text color', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='cardblock',
            name='icon_layout',
            field=models.CharField(choices=[('side-by-side', 'Side by Side (Icon Left, Title Right)'), ('top-down', 'Top Down (Icon Top, Title Bottom)')], default='top-down', help_text='How icon and title are displayed', max_length=20),
        ),
        migrations.AddField(
            model_name='section',
            name='title_font_size',
            field=models.CharField(default='2xl', help_text='Title font size (e.g., sm, md, lg, xl, 2xl, 3xl, 4xl,6xl)', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='header_bg_color',
            field=colorfield.fields.ColorField(default='#ffffff', help_text='Header background color', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='header_text_color',
            field=colorfield.fields.ColorField(default='#000000', help_text='Header text color', image_field=None, max_length=25, samples=None),
        ),
    ]
