# Generated by Django 5.2.8 on 2025-11-14 21:09

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_cardblock_card_bg_color_cardblock_card_text_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardblock',
            name='button_color',
            field=colorfield.fields.ColorField(blank=True, default='#3b82f6', help_text='Button color in HEX format', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='cardblock',
            name='button_text_color',
            field=colorfield.fields.ColorField(blank=True, default='#ffffff', help_text='Button text color in HEX format', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='cardblock',
            name='card_bg_color',
            field=colorfield.fields.ColorField(blank=True, default='#ffffff', help_text='Card background color', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='cardblock',
            name='card_text_color',
            field=colorfield.fields.ColorField(blank=True, default='#000000', help_text='Card text color', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='cardblock',
            name='icon',
            field=models.CharField(blank=True, help_text='Lucide icon name (e.g. rocket-launch)', max_length=60),
        ),
        migrations.AlterField(
            model_name='cardblock',
            name='icon_color',
            field=colorfield.fields.ColorField(blank=True, default='#3b82f6', help_text='Icon color in HEX format', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='cardblock',
            name='icon_size',
            field=models.PositiveIntegerField(blank=True, default=32, help_text='Icon size in pixels'),
        ),
    ]
