# Generated by Django 5.2.8 on 2025-11-15 07:46

import colorfield.fields
import django.core.validators
import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_cardblock_button_color_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cardblock',
            options={'ordering': ['order'], 'verbose_name_plural': 'Card Blocks'},
        ),
        migrations.AlterModelOptions(
            name='hero',
            options={'ordering': ['order'], 'verbose_name_plural': 'Hero Sections'},
        ),
        migrations.AlterModelOptions(
            name='herobackgroundimage',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='rotatingtextitem',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['order'], 'verbose_name_plural': 'Sections'},
        ),
        migrations.AlterField(
            model_name='cardblock',
            name='button_color',
            field=colorfield.fields.ColorField(default='#3b82f6', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='cardblock',
            name='button_target',
            field=models.CharField(choices=[('_self', 'Same Tab'), ('_blank', 'New Tab')], default='_self', max_length=10),
        ),
        migrations.AlterField(
            model_name='cardblock',
            name='button_text_color',
            field=colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='cardblock',
            name='card_bg_color',
            field=colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='cardblock',
            name='card_text_color',
            field=colorfield.fields.ColorField(default='#000000', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='cardblock',
            name='icon',
            field=models.CharField(blank=True, max_length=60, validators=[django.core.validators.RegexValidator('^[a-z0-9-]+$', 'Lucide icon name must be kebab-case (e.g. rocket-launch).')]),
        ),
        migrations.AlterField(
            model_name='cardblock',
            name='icon_color',
            field=colorfield.fields.ColorField(default='#3b82f6', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='cardblock',
            name='icon_layout',
            field=models.CharField(choices=[('side-by-side', 'Side by Side'), ('top-down', 'Top Down')], default='top-down', max_length=20),
        ),
        migrations.AlterField(
            model_name='cardblock',
            name='icon_size',
            field=models.PositiveIntegerField(default=32),
        ),
        migrations.AlterField(
            model_name='cardblock',
            name='text',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True),
        ),
        migrations.AlterField(
            model_name='cardblock',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='hero',
            name='bg_color',
            field=colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='hero',
            name='cta_bg_color',
            field=colorfield.fields.ColorField(default='#3b82f6', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='hero',
            name='cta_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='hero',
            name='cta_text',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='hero',
            name='image_settimeout',
            field=models.PositiveIntegerField(default=5000),
        ),
        migrations.AlterField(
            model_name='hero',
            name='layout_type',
            field=models.CharField(choices=[('text-left-image-right', 'Text Left / Image Right'), ('text-right-image-left', 'Text Right / Image Left'), ('text-center-image-background', 'Text Center / Image Background'), ('text-center-no-image', 'Text Center / No Image')], default='text-center-image-background', max_length=50),
        ),
        migrations.AlterField(
            model_name='hero',
            name='rotating_text_settimeout',
            field=models.PositiveIntegerField(default=3000),
        ),
        migrations.AlterField(
            model_name='hero',
            name='subtitle_description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True),
        ),
        migrations.AlterField(
            model_name='hero',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='herobackgroundimage',
            name='hero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='background_images', to='core.hero'),
        ),
        migrations.AlterField(
            model_name='herobackgroundimage',
            name='image',
            field=models.ImageField(upload_to='hero_backgrounds/'),
        ),
        migrations.AlterField(
            model_name='herobackgroundimage',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='navigationitem',
            name='button_target',
            field=models.CharField(choices=[('_self', 'Same Tab'), ('_blank', 'New Tab')], default='_self', max_length=10),
        ),
        migrations.AlterField(
            model_name='rotatingtextitem',
            name='hero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotating_texts', to='core.hero'),
        ),
        migrations.AlterField(
            model_name='rotatingtextitem',
            name='text',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='section',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='layout',
            field=models.CharField(choices=[('hero', 'Hero'), ('grid-3', '3-Col Cards'), ('stats', 'Stats Grid'), ('list', 'Bullet List')], default='grid-3', max_length=20),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='section',
            name='title_font_size',
            field=models.CharField(default='2xl', max_length=20),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='header_bg_color',
            field=colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='header_text_color',
            field=colorfield.fields.ColorField(default='#000000', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo_text',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(default='EthioSites', max_length=100),
        ),
    ]
