# Generated by Django 5.2.8 on 2025-11-15 07:47

import colorfield.fields
import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_cardblock_options_alter_hero_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cardblock',
            options={'ordering': ['order'], 'verbose_name': 'Card Block', 'verbose_name_plural': 'Card Blocks'},
        ),
        migrations.AlterModelOptions(
            name='hero',
            options={'ordering': ['order'], 'verbose_name': 'Hero Section', 'verbose_name_plural': 'Hero Sections'},
        ),
        migrations.AlterModelOptions(
            name='herobackgroundimage',
            options={'ordering': ['order'], 'verbose_name': 'Hero Background Image', 'verbose_name_plural': 'Hero Background Images'},
        ),
        migrations.AlterModelOptions(
            name='rotatingtextitem',
            options={'ordering': ['order'], 'verbose_name': 'Rotating Text Item', 'verbose_name_plural': 'Rotating Text Items'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['order'], 'verbose_name': 'Section', 'verbose_name_plural': 'Sections'},
        ),
        migrations.AlterField(
            model_name='cardblock',
            name='button_color',
            field=colorfield.fields.ColorField(blank=True, default='#3b82f6', help_text='Button color in HEX format', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='cardblock',
            name='button_target',
            field=models.CharField(blank=True, choices=[('_self', 'Same Tab'), ('_blank', 'New Tab')], default='_self', max_length=10),
        ),
        migrations.AlterField(
            model_name='cardblock',
            name='button_text_color',
            field=colorfield.fields.ColorField(blank=True, default='#ffffff', help_text='Button text color in HEX format', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='cardblock',
            name='card_bg_color',
            field=colorfield.fields.ColorField(blank=True, default='#ffffff', help_text='Card background color', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='cardblock',
            name='card_text_color',
            field=colorfield.fields.ColorField(blank=True, default='#000000', help_text='Card text color', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='cardblock',
            name='icon',
            field=models.CharField(blank=True, help_text='Lucide icon name (e.g. rocket-launch)', max_length=60),
        ),
        migrations.AlterField(
            model_name='cardblock',
            name='icon_color',
            field=colorfield.fields.ColorField(blank=True, default='#3b82f6', help_text='Icon color in HEX format', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='cardblock',
            name='icon_layout',
            field=models.CharField(choices=[('side-by-side', 'Side by Side (Icon Left, Title Right)'), ('top-down', 'Top Down (Icon Top, Title Bottom)')], default='top-down', help_text='How icon and title are displayed', max_length=20),
        ),
        migrations.AlterField(
            model_name='cardblock',
            name='icon_size',
            field=models.PositiveIntegerField(blank=True, default=32, help_text='Icon size in pixels'),
        ),
        migrations.AlterField(
            model_name='cardblock',
            name='text',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Rich text content for the card'),
        ),
        migrations.AlterField(
            model_name='cardblock',
            name='title',
            field=models.CharField(help_text='Card title displayed prominently', max_length=200),
        ),
        migrations.AlterField(
            model_name='hero',
            name='bg_color',
            field=colorfield.fields.ColorField(default='#ffffff', help_text='Background color for the Hero section', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='hero',
            name='cta_bg_color',
            field=colorfield.fields.ColorField(default='#3b82f6', help_text='Button background color', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='hero',
            name='cta_link',
            field=models.URLField(blank=True, help_text='Call-to-Action button URL'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='cta_text',
            field=models.CharField(blank=True, help_text='Call-to-Action button text', max_length=100),
        ),
        migrations.AlterField(
            model_name='hero',
            name='image_settimeout',
            field=models.PositiveIntegerField(default=5000, help_text='Delay (ms) for background image rotation'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='layout_type',
            field=models.CharField(choices=[('text-left-image-right', 'Text Left / Image Right'), ('text-right-image-left', 'Text Right / Image Left'), ('text-center-image-background', 'Text Center / Image Background'), ('text-center-no-image', 'Text Center / No Image')], default='text-center-image-background', help_text='Descriptive layout type', max_length=50),
        ),
        migrations.AlterField(
            model_name='hero',
            name='rotating_text_settimeout',
            field=models.PositiveIntegerField(default=3000, help_text='Delay (ms) for text rotation'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='subtitle_description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Supporting text. Rich text editor enabled.'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='title',
            field=models.CharField(help_text='Main heading. Plain text (no rich text editor).', max_length=200),
        ),
        migrations.AlterField(
            model_name='herobackgroundimage',
            name='hero',
            field=models.ForeignKey(help_text='Parent Hero section', on_delete=django.db.models.deletion.CASCADE, related_name='background_images', to='core.hero'),
        ),
        migrations.AlterField(
            model_name='herobackgroundimage',
            name='image',
            field=models.ImageField(help_text='Image file for the background slider', upload_to='hero_backgrounds/'),
        ),
        migrations.AlterField(
            model_name='herobackgroundimage',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Used for sorting the slide rotation'),
        ),
        migrations.AlterField(
            model_name='navigationitem',
            name='button_target',
            field=models.CharField(blank=True, choices=[('_self', 'Same Tab'), ('_blank', 'New Tab')], default='_self', max_length=10),
        ),
        migrations.AlterField(
            model_name='rotatingtextitem',
            name='hero',
            field=models.ForeignKey(help_text='Parent Hero section', on_delete=django.db.models.deletion.CASCADE, related_name='rotating_texts', to='core.hero'),
        ),
        migrations.AlterField(
            model_name='rotatingtextitem',
            name='text',
            field=models.CharField(help_text='The individual text string to be rotated', max_length=200),
        ),
        migrations.AlterField(
            model_name='section',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Description of this content section'),
        ),
        migrations.AlterField(
            model_name='section',
            name='layout',
            field=models.CharField(choices=[('hero', 'Hero'), ('grid-3', '3-Col Cards'), ('stats', 'Stats Grid'), ('list', 'Bullet List')], default='grid-3', help_text='Layout template used to display this section', max_length=20),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(help_text='Descriptive name for this content section', max_length=100),
        ),
        migrations.AlterField(
            model_name='section',
            name='title_font_size',
            field=models.CharField(default='2xl', help_text='Title font size (e.g., sm, md, lg, xl, 2xl, 3xl, 4xl,6xl)', max_length=20),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='header_bg_color',
            field=colorfield.fields.ColorField(default='#ffffff', help_text='Header background color', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='header_text_color',
            field=colorfield.fields.ColorField(default='#000000', help_text='Header text color', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, help_text='Upload your logo image', null=True, upload_to='logos/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo_text',
            field=models.CharField(blank=True, help_text='e.g., [Logo] or leave blank', max_length=50),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(default='Ethiotech Leader', max_length=100),
        ),
    ]
