# Generated by Django 5.2.8 on 2025-11-15 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_cardblock_options_alter_hero_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardblock',
            name='icon_layout',
            field=models.CharField(choices=[('side-by-side', 'Side by Side (Icon Left, Title Right)'), ('top-down', 'Top Down (Icon Top, Title Bottom)'), ('top-down-center', 'Top Down (Icon Center, Title Center)')], default='top-down', help_text='How icon and title are displayed', max_length=20),
        ),
    ]
