# Generated by Django 5.2.8 on 2025-11-15 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_cardblock_icon_layout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='layout',
        ),
        migrations.AddField(
            model_name='section',
            name='section_type',
            field=models.CharField(choices=[('default', 'Default Grid'), ('hero', 'Hero Section'), ('stats', 'Statistics'), ('testimonials', 'Testimonials'), ('features', 'Features'), ('cta', 'Call to Action'), ('team', 'Team Members'), ('pricing', 'Pricing Plans'), ('faq', 'Frequently Asked Questions'), ('contact', 'Contact Form')], default='default', help_text='Predefined section template type', max_length=50),
        ),
    ]
