# Generated by Django 5.2.8 on 2025-11-15 17:02

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_section_layout_section_section_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='button_color',
            field=colorfield.fields.ColorField(blank=True, default='#3b82f6', help_text='Button background color', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='section',
            name='button_label',
            field=models.CharField(blank=True, help_text='Text for the section button', max_length=100),
        ),
        migrations.AddField(
            model_name='section',
            name='button_target',
            field=models.CharField(blank=True, choices=[('_self', 'Same Tab'), ('_blank', 'New Tab')], default='_self', max_length=10),
        ),
        migrations.AddField(
            model_name='section',
            name='button_text_color',
            field=colorfield.fields.ColorField(blank=True, default='#ffffff', help_text='Button text color', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='section',
            name='button_url',
            field=models.URLField(blank=True, help_text='URL for the section button'),
        ),
    ]
