# Generated by Django 5.2.8 on 2025-11-15 17:09

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_section_button_color_section_button_label_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='button_target',
            new_name='cta_target',
        ),
        migrations.RemoveField(
            model_name='section',
            name='button_color',
        ),
        migrations.RemoveField(
            model_name='section',
            name='button_label',
        ),
        migrations.RemoveField(
            model_name='section',
            name='button_text_color',
        ),
        migrations.RemoveField(
            model_name='section',
            name='button_url',
        ),
        migrations.AddField(
            model_name='section',
            name='cta_bg_color',
            field=colorfield.fields.ColorField(blank=True, default='#3b82f6', help_text='CTA background color', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='section',
            name='cta_label',
            field=models.CharField(blank=True, help_text='Text for the section CTA', max_length=100),
        ),
        migrations.AddField(
            model_name='section',
            name='cta_text_color',
            field=colorfield.fields.ColorField(blank=True, default='#ffffff', help_text='CTA text color', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='section',
            name='cta_url',
            field=models.URLField(blank=True, help_text='URL for the section CTA'),
        ),
    ]
