# Generated by Django 5.2.8 on 2025-11-17 13:38

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_button_target_section_cta_target_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardblock',
            name='button_label_am',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cardblock',
            name='button_label_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        
        migrations.AddField(
            model_name='cardblock',
            name='button_url_am',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cardblock',
            name='button_url_en',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cardblock',
            name='title_am',
            field=models.CharField(help_text='Card title displayed prominently', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cardblock',
            name='title_en',
            field=models.CharField(help_text='Card title displayed prominently', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hero',
            name='bg_color_am',
            field=colorfield.fields.ColorField(blank=True, default='#ffffff', help_text='Background color for the Hero section', image_field=None, max_length=25, null=True, samples=None),
        ),
        migrations.AddField(
            model_name='hero',
            name='bg_color_en',
            field=colorfield.fields.ColorField(blank=True, default='#ffffff', help_text='Background color for the Hero section', image_field=None, max_length=25, null=True, samples=None),
        ),
        migrations.AddField(
            model_name='hero',
            name='cta_text_am',
            field=models.CharField(blank=True, help_text='Call-to-Action button text', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hero',
            name='cta_text_en',
            field=models.CharField(blank=True, help_text='Call-to-Action button text', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hero',
            name='title_am',
            field=models.CharField(help_text='Main heading. Plain text (no rich text editor).', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hero',
            name='title_en',
            field=models.CharField(help_text='Main heading. Plain text (no rich text editor).', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='navigationitem',
            name='label_am',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='navigationitem',
            name='label_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rotatingtextitem',
            name='text_am',
            field=models.CharField(help_text='The individual text string to be rotated', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rotatingtextitem',
            name='text_en',
            field=models.CharField(help_text='The individual text string to be rotated', max_length=200, null=True),
        ),
            migrations.AddField(
            model_name='section',
            name='cta_label_am',
            field=models.CharField(blank=True, help_text='Text for the section CTA', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='cta_label_en',
            field=models.CharField(blank=True, help_text='Text for the section CTA', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='name_am',
            field=models.CharField(help_text='Descriptive name for this content section', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='name_en',
            field=models.CharField(help_text='Descriptive name for this content section', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='section_bg_color_am',
            field=colorfield.fields.ColorField(blank=True, default='#ffffff', image_field=None, max_length=25, null=True, samples=None),
        ),
        migrations.AddField(
            model_name='section',
            name='section_bg_color_en',
            field=colorfield.fields.ColorField(blank=True, default='#ffffff', image_field=None, max_length=25, null=True, samples=None),
        ),
        migrations.AddField(
            model_name='section',
            name='section_text_color_am',
            field=colorfield.fields.ColorField(blank=True, default='#000000', image_field=None, max_length=25, null=True, samples=None),
        ),
        migrations.AddField(
            model_name='section',
            name='section_text_color_en',
            field=colorfield.fields.ColorField(blank=True, default='#000000', image_field=None, max_length=25, null=True, samples=None),
        ),
        migrations.AddField(
            model_name='section',
            name='title_font_size_am',
            field=models.CharField(default='2xl', help_text='Title font size (e.g., sm, md, lg, xl, 2xl, 3xl, 4xl,6xl)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='title_font_size_en',
            field=models.CharField(default='2xl', help_text='Title font size (e.g., sm, md, lg, xl, 2xl, 3xl, 4xl,6xl)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_name_am',
            field=models.CharField(default='Ethiotech Leader', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_name_en',
            field=models.CharField(default='Ethiotech Leader', max_length=100, null=True),
        ),
    ]
