# Generated by Django 5.2.8 on 2025-11-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_cardblock_button_label_am_cardblock_button_label_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardblock',
            name='text',
            field=models.TextField(blank=True, help_text='Rich text content for the card'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='subtitle_description',
            field=models.TextField(blank=True, help_text='Supporting text. Rich text editor enabled.'),
        ),
        migrations.AlterField(
            model_name='section',
            name='description',
            field=models.TextField(blank=True, help_text='Description of this content section'),
        ),
    ]
