# Generated by Django 5.2.8 on 2025-11-17 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_cardblock_text_alter_hero_subtitle_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardblock',
            name='text_am',
            field=models.TextField(blank=True, help_text='Rich text content for the card', null=True),
        ),
        migrations.AddField(
            model_name='cardblock',
            name='text_en',
            field=models.TextField(blank=True, help_text='Rich text content for the card', null=True),
        ),
        migrations.AddField(
            model_name='hero',
            name='subtitle_description_am',
            field=models.TextField(blank=True, help_text='Supporting text. Rich text editor enabled.', null=True),
        ),
        migrations.AddField(
            model_name='hero',
            name='subtitle_description_en',
            field=models.TextField(blank=True, help_text='Supporting text. Rich text editor enabled.', null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='description_am',
            field=models.TextField(blank=True, help_text='Description of this content section', null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='description_en',
            field=models.TextField(blank=True, help_text='Description of this content section', null=True),
        ),
    ]
