# Generated by Django 5.2.8 on 2025-11-17 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_cardblock_text_am_cardblock_text_en_and_more'),
    ]

    operations = [
       
    ]
