# Generated by Django 5.2.7 on 2025-11-18 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_cardblock_text_so_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='bg_color_am',
        ),
        migrations.RemoveField(
            model_name='hero',
            name='bg_color_en',
        ),
        migrations.RemoveField(
            model_name='section',
            name='section_bg_color_am',
        ),
        migrations.RemoveField(
            model_name='section',
            name='section_bg_color_en',
        ),
        migrations.RemoveField(
            model_name='section',
            name='section_text_color_am',
        ),
        migrations.RemoveField(
            model_name='section',
            name='section_text_color_en',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='address',
            field=models.CharField(blank=True, help_text='Company address', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='address_am',
            field=models.CharField(blank=True, help_text='Company address', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='address_en',
            field=models.CharField(blank=True, help_text='Company address', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='description',
            field=models.TextField(blank=True, help_text='Site description for footer'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='description_am',
            field=models.TextField(blank=True, help_text='Site description for footer', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='description_en',
            field=models.TextField(blank=True, help_text='Site description for footer', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email',
            field=models.EmailField(blank=True, help_text='Contact email', max_length=254),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='facebook_url',
            field=models.URLField(blank=True, help_text='Facebook page URL'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='instagram_url',
            field=models.URLField(blank=True, help_text='Instagram profile URL'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='LinkedIn profile URL'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='logo_text_am',
            field=models.CharField(blank=True, help_text='e.g., [Logo] or leave blank', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='logo_text_en',
            field=models.CharField(blank=True, help_text='e.g., [Logo] or leave blank', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='opening_hours',
            field=models.TextField(blank=True, help_text='Opening hours (use line breaks for multiple lines)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='phone',
            field=models.CharField(blank=True, help_text='Contact phone number', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='twitter_url',
            field=models.URLField(blank=True, help_text='Twitter profile URL'),
        ),
        migrations.AlterField(
            model_name='section',
            name='section_type',
            field=models.CharField(choices=[('default', 'Default Grid'), ('hero', 'Hero Section'), ('stats', 'Statistics'), ('impact', 'Impact'), ('testimonials', 'Testimonials'), ('features', 'Features'), ('cta', 'Call to Action'), ('team', 'Team Members'), ('pricing', 'Pricing Plans'), ('faq', 'Frequently Asked Questions'), ('contact', 'Contact Form')], default='default', help_text='Predefined section template type', max_length=50),
        ),
    ]
