# Generated by Django 5.2.7 on 2025-11-18 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_hero_bg_color_am_remove_hero_bg_color_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, help_text='Site description for footer')),
                ('description_en', models.TextField(blank=True, help_text='Site description for footer', null=True)),
                ('description_am', models.TextField(blank=True, help_text='Site description for footer', null=True)),
                ('address', models.CharField(blank=True, help_text='Company address', max_length=200)),
                ('address_en', models.CharField(blank=True, help_text='Company address', max_length=200, null=True)),
                ('address_am', models.CharField(blank=True, help_text='Company address', max_length=200, null=True)),
                ('phone', models.CharField(blank=True, help_text='Contact phone number', max_length=20)),
                ('email', models.EmailField(blank=True, help_text='Contact email', max_length=254)),
                ('opening_hours', models.TextField(blank=True, help_text='Opening hours (use line breaks for multiple lines)')),
                ('facebook_url', models.URLField(blank=True, help_text='Facebook page URL')),
                ('twitter_url', models.URLField(blank=True, help_text='Twitter profile URL')),
                ('instagram_url', models.URLField(blank=True, help_text='Instagram profile URL')),
                ('linkedin_url', models.URLField(blank=True, help_text='LinkedIn profile URL')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Footer',
                'verbose_name_plural': 'Footer',
            },
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='address',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='address_am',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='address_en',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='description',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='description_am',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='email',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='facebook_url',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='instagram_url',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='linkedin_url',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='opening_hours',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='twitter_url',
        ),
    ]
