# Generated by Django 5.2.7 on 2025-11-18 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_footer_remove_sitesettings_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardblock',
            name='button_label',
        ),
        migrations.RemoveField(
            model_name='cardblock',
            name='button_label_am',
        ),
        migrations.RemoveField(
            model_name='cardblock',
            name='button_label_en',
        ),
        migrations.RemoveField(
            model_name='cardblock',
            name='button_url',
        ),
        migrations.RemoveField(
            model_name='cardblock',
            name='button_url_am',
        ),
        migrations.RemoveField(
            model_name='cardblock',
            name='button_url_en',
        ),
        migrations.AddField(
            model_name='cardblock',
            name='cta_label',
            field=models.CharField(blank=True, help_text='Call-to-Action label text', max_length=100),
        ),
        migrations.AddField(
            model_name='cardblock',
            name='cta_label_am',
            field=models.CharField(blank=True, help_text='Call-to-Action label text', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cardblock',
            name='cta_label_en',
            field=models.CharField(blank=True, help_text='Call-to-Action label text', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cardblock',
            name='cta_url',
            field=models.URLField(blank=True, help_text='Call-to-Action URL link'),
        ),
        migrations.AddField(
            model_name='cardblock',
            name='cta_url_am',
            field=models.URLField(blank=True, help_text='Call-to-Action URL link', null=True),
        ),
        migrations.AddField(
            model_name='cardblock',
            name='cta_url_en',
            field=models.URLField(blank=True, help_text='Call-to-Action URL link', null=True),
        ),
    ]
