# Generated by Django 5.2.8 on 2025-11-18 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_cardblock_button_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigationitem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
