# Generated by Django 5.2.8 on 2025-11-18 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_navigationitem_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigationitem',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the navigation item'),
        ),
    ]
