# Generated by Django 5.2.8 on 2025-11-18 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_navigationitem_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navigationitem',
            name='button_label',
        ),
        migrations.RemoveField(
            model_name='navigationitem',
            name='button_url',
        ),
    ]
