# Generated by Django 5.2.8 on 2025-11-18 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_navigationitem_button_label_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navigationitem',
            name='button_target',
        ),
    ]
