# Generated by Django 5.2.8 on 2025-11-18 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_navigationitem_button_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigationitem',
            name='description_am',
            field=models.TextField(blank=True, help_text='Description of the navigation item', null=True),
        ),
        migrations.AddField(
            model_name='navigationitem',
            name='description_en',
            field=models.TextField(blank=True, help_text='Description of the navigation item', null=True),
        ),
    ]
