# Generated by Django 4.2.3 on 2023-07-15 10:30

from django.db import migrations, models
import django.utils.timezone

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_navigationitem_description_am_and_more'),
    ]

    operations = [
        # Add fields to Section
        migrations.AddField(
            model_name='section',
            name='view_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times this section has been viewed'),
        ),
        migrations.AddField(
            model_name='section',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        
        # Add fields to CardBlock
        migrations.AddField(
            model_name='cardblock',
            name='click_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times CTA link has been clicked'),
        ),
        migrations.AddField(
            model_name='cardblock',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cardblock',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        
        # Add fields to Hero
        migrations.AddField(
            model_name='hero',
            name='view_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times this hero section has been viewed'),
        ),
        migrations.AddField(
            model_name='hero',
            name='cta_click_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times CTA button has been clicked'),
        ),
        migrations.AddField(
            model_name='hero',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hero',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        
        # Add fields to NavigationItem
        migrations.AddField(
            model_name='navigationitem',
            name='click_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times this navigation item has been clicked'),
        ),
        migrations.AddField(
            model_name='navigationitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='navigationitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]